[server]
maxUploadSize = 5
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
magicEnabled = false
fastReruns = true

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#111827"
backgroundColor = "#f9fafb"
secondaryBackgroundColor = "#ffffff"
textColor = "#111827"
